{{- if .Values.secretEnv.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-playwright-helm.fullname" . }}
  labels:
    {{- include "mcp-playwright-helm.labels" . | nindent 4 }}
type: Opaque
# NOTE: For production deployments, prefer managing sensitive data in existing Secrets
# or through an external secret manager instead of embedding it directly in values files.
data:
  {{- range $key, $val := .Values.secretEnv.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
