{{- if .Values.secretEnv.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-env" (include "mcp-atlassian-helm.fullname" .)) .Values.secretEnv.name }}
  labels:
    {{- include "mcp-atlassian-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnv.data }}
  {{- if or (eq (trim $key) "") (eq (toString $val) "") }}
  {{- fail (printf "secretEnv.data entry for key '%s' must not be empty" $key) }}
  {{- end }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
