replicaCount: 1

image:
  repository: nghyane/copilot-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4141
  # May be a numeric container port or a named port exposed by the container.
  targetPort: 4141

ingress:
  enabled: false
  className: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - copilot-api.local
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: ""

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

envSecrets: {}

secretEnv:
  data: {}

auth:
  tokenSecret:
    create: true
    name: ""
    key: GH_TOKEN
    value: ""
    valueBase64: ""
    # Generates a placeholder value when no token is supplied. Override with a real token in production.
    generate: true
    reuseExisting: true
    forceRegenerate: false
    existingSecret: ""
    existingSecretKey: ""
    annotations: {}
