{{- if .Values.secretEnv.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-copilot-api-helm.fullname" . }}
  labels:
    {{- include "mcp-copilot-api-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnv.data }}
  {{- if not (regexMatch "^[A-Za-z_][A-Za-z0-9_]*$" $key) }}
    {{- fail (printf "secretEnv.data key '%s' must match ^[A-Za-z_][A-Za-z0-9_]*$" $key) -}}
  {{- end }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
