{{- if and .Values.config.enabled .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search.fullname" . }}-config
  labels:
    {{- include "search.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}
