apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "search-helm-chart.fullname" . }}
  labels:
    {{- include "search-helm-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "search-helm-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}