apiVersion: v1
kind: Secret
metadata:
  name: search-tool-secret
type: Opaque
data:
  # Add your sensitive data here, encoded in base64
  # For example:
  # password: <base64_encoded_password>
  # api_key: <base64_encoded_api_key>
  # Example:
  # password: cGFzc3dvcmQ=  # base64 for 'password'