name: Helm Chart Lint

on:
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - name: Add MCP chart repository
        run: |
          helm repo add mcp https://arbuzov.github.io/mcp-helm/
          helm repo update

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint '**/*.md'

      - name: Lint all charts
        run: |
          status=0
          for chart in charts/*; do
            helm dependency update "$chart" || true
            helm lint "$chart" || status=1
          done
          exit $status

      - name: Install kubeval
        run: |
          curl -L https://github.com/instrumenta/kubeval/releases/download/v0.16.1/kubeval-linux-amd64.tar.gz -o kubeval.tar.gz
          tar xzf kubeval.tar.gz
          sudo install -o root -g root -m 0755 kubeval /usr/local/bin/kubeval

      - name: Render and validate charts
        run: |
          status=0
          for chart in charts/*; do
            helm template "$chart" | kubeval - --ignore-missing-schemas || status=1
          done
          exit $status

      - name: Install yq
        run: |
          YQ_VERSION=4.43.1
          curl -L https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 -o yq
          sudo install -o root -g root -m 0755 yq /usr/local/bin/yq

      - name: Check Artifact Hub readiness
        run: ./scripts/check-artifacthub.sh
